[package]
name = "tlacuache"
description = "Gestor de archivos con columnas Miller, doble panel y terminal integrada"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
tlacuache-core.workspace = true
gtk.workspace = true
adw.workspace = true
glib.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
glib-build-tools.workspace = true
